### ISSUE TITLE
[Talk Proposal] Web 3.0 with IPFS

### ISSUE THREAD

**Issue by aeddi** [francep2p/community#21]
#### Title

Web 3.0 with IPFS

#### Languages

- [x] 🇫🇷
- [x] 🇬🇧

#### Estimated duration (max 20 min)

~15 min

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None | [ ] None | [✓] None | [ ] None |
| [✓] Beginner | [✓] Beginner | [ ] Beginner | [ ] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [✓] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory)
- [x] Yes (if possible)
- [ ] No

---
## Description of your talk

I will present an IPFS overview, the solutions it provides to decentralize / distribute the web and the issues it faces, explaining the different underlying technical concepts in a way accessible to a neophyte.

Here is a presentation plan:

Current web:
- How the current web works?
- What are the problems of the current web?

Web 3.0:
- Key concepts:
   - Public key cryptography
   - Cryptographic hashes
   - Swarm / p2p network
- IPFS overview:
   - PeerID
   - CID
   - Content addressed
   - Name system
   - Content pinning
   - Use cases

---

## About you

* **Name:** Antoine Eddi
* **Matrix handle:** @aeddi-berty
* **Discord handle:** @aeddi#1523
* **Other contact info:** antoine@berty.tech
* **Links to your previous talks:** N/A
* **Other (your projects, etc...):** [Berty](https://berty.tech/)
* **Availability (monthly number):** 3, 4, ..., ∞

**Comment by catwell** [comment]
If you do an IPFS talk I hope you talk about how you can replace non-GET HTTP verbs as well (e.g. how do you submit a form, make a comments system...).

Most most talks about IPFS I have seen get into technical implementation details, and at the end you are left with "OK, that can let me distribute my front-end code, but that's the easy part... what about the backend?".

**Comment by aeddi** [comment]
> If you do an IPFS talk I hope you talk about how you can replace non-GET HTTP verbs as well (e.g. how do you submit a form, make a comments system...).

I don't intend to discuss these topics in this talk, sorry :)
In fact, I plan to address topics such as: differences in terms of trust model, connection model, content routing, etc... So a layer underneath the application development.

The goal of the talk is to be less than 20 min while remaining accessible to neophytes. And I think it's better to start with an intro of this type before moving on to the higher level considerations.

But it might be a good idea to follow up with a talk on "How to develop a webapp on top of IPFS", at a later event or why not, if someone is motivated to do so, during the same event, right after this introductory talk.

**Comment by moul** [comment]
This talk is announced for Paris-P2P-#2 on 2019-10-02

-> https://p2p.paris/en/event/monthly-2/

**Comment by moul** [comment]
Announced in #37 and here: https://p2p.paris/en/event/monthly-2/

**Comment by moul** [comment]
Nice talk, @aeddi can you upload the slides somewhere and put a link in this issue?

Thanks!
