### ISSUE TITLE
[Workshop Proposal] Introduction to Crypto Wallet (Beginners) Workshop by @LesHackeuses

### ISSUE THREAD

**Issue by zooma2k18** [francep2p/community#24]
#### Title

Introduction to Crypto Wallet (Beginners) Workshop by @LesHackeuses

#### Workshop type

- [ ] Debate
- [x] Hands-on
- [ ] [Poster creation](https://github.com/parisp2p/community/wiki/Poster-workshop)
- [ ] Course

#### Languages

- [x] 🇫🇷
- [ ] 🇬🇧

#### Required knowledge level
  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [x] None     | [x] None     | [x] None     | [ ] None     |
| [ ] Beginner | [ ] Beginner | [ ] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Prerequisites for participants

- bring your laptop or phone

---

## Description of your workshop

The workshop will take place during the "FFA" part of the Paris P2P (after the traditional "person-to-person" of P2P meetings) and is open to all. Intended for beginners wishing to learn how to use a cryptocurrency, it does not require any special skills. 
Usually reserved for women, this workshop will teach you how to install and create a wallet on your device, basic security principles, and perform your first transactions on a testnet network (OSM).

* intro: <5 min
  * Quick introduction by Mamie Crypto to the approach of the association @LesHackeuses, defending the place of women in the world of technology, blockchain and crypto-currencies
  * Invitation to participate in a workshop to  familiarize yourself with a crypto wallet.
* workshop: no time-limit
  * Free workshop during the FFA session

---

## About you

* Name: **Mamie Crypto** 
* Matrix handle: **N/A** 
* Discord handle: **Mamie Crypto #8721**  
* Other contact info: **www.leshackeuses.fr** 
* Other (your projects, etc...): **https://leshackeuses.fr/decouvrir/presse-on-parle-de-nous** 
* Availability (monthly number, date): **2/10/2019 @ Paris P2P ~3**

**Comment by moul** [comment]
Announced in #37 and here: https://p2p.paris/en/event/monthly-2/
