### ISSUE TITLE
[Workshop Proposal] Delegate Proof-of-Stake 

### ISSUE THREAD

**Issue by zooma2k18** [francep2p/community#31]
#### Title

Delegate Proof-of-Stake Protocol (Blockchain)

#### Workshop type

- [ ] Debate
- [ ] Hands-on
- [x] [Poster creation](https://github.com/parisp2p/community/wiki/Poster-workshop)
- [ ] Course

#### Languages

- [x] 🇫🇷
- [ ] 🇬🇧

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [x] Beginner | [x] Beginner | [x] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Prerequisites for participants

Nothing special (!) Just bring your smile & brain ?

---

## Description of your workshop

Let's talk together about DPOS, and try to explain it to a kid (or not).
What's Delegate Proof-of-Stake Protocol ?
Differences with Proof-of-Work 
DPOS : State of the art and Mainnet examples 

---

## About you

* Name: **zôÖma** 
* Matrix handle: **NC** 
* Discord handle: **zôÖma #1773**  
* Other contact info: **@ Paris P2P :)** 
* Other (your projects, etc...): **www.osmose.world** 
* Availability (monthly number, date): **ParisP2P_#3 - 2/10/2019**

**Comment by moul** [comment]
Announced in #37 and here: https://p2p.paris/en/event/monthly-2/

**Comment by moul** [comment]
This "poster session' was quite funny, more like a "pizza-box session" :)

@zooma2k18, can you upload a photo here?
