### ISSUE TITLE
[Talk Proposal] DPOS : Under the hood

### ISSUE THREAD

**Issue by louptheron** [francep2p/community#32]
#### Title

DPOS : Under the hood

#### Languages

- [x] 🇫🇷
- [ ] 🇬🇧

#### Estimated duration

~15 min

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [x] Beginner | [x] Beginner | [x] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory)
- [x] Yes (if possible)
- [ ] No

---

## Description of your talk

After the talk about DPOS by @zooma2k18, we'll try to see how these consensus are implemented - in at least one blockchain - and explain the main differences betweem the various implementations.

---

## About you

* Name: **Loup**
* Matrix handle: **NC** 
* Discord handle: **lth #2150**  
* Other (your projects, etc...): **www.osmose.world** 
* Availability (monthly number, date): **ParisP2P_#3 - 2/10/2019**

**Comment by zooma2k18** [comment]
Just for precision, I'll not give a talk, but a "poster session", a kind of collaborative explanation & exploration of the subject with a poster, a every kind of public can join the workshop (beginners to experts). The aim is to explore the subject to synthetize it at the end for a general public with a simple poster (hard exercice :D).

Great idea @louptheron to add a dedicated talk just after, the poster session can bring an introduction for new comers :) 👍

**Comment by moul** [comment]
Yep, definitely a good idea to start with the poster session, and then, have an under the hood explanation so that everyone can have a deeper understanding after those two steps

**Comment by louptheron** [comment]
@moul Could I add this to [2019-10-02's event](https://github.com/parisp2p/community/issues/37) ?

**Comment by moul** [comment]
We already have too many talks on this date

Options are:
1. that you find another date
2. that we move @aeddi's talk to another date so you can take his place

cc @aeddi

**Comment by louptheron** [comment]
Got it, first option (https://github.com/parisp2p/community/issues/38) is also OK for me

**Comment by moul** [comment]
Cool, we have a B plan :)

@aeddi, can we move your talk to the next event (#38)? -> this way, @louptheron will make a DPOS talk the same day of the DPOS poster session (#31)

**Comment by moul** [comment]
Announced here: https://github.com/francep2p/community/issues/38

and on here: https://p2p.paris/en/event/monthly-3/ (PR here: https://github.com/francep2p/p2p.paris/pull/45)

**Comment by moul** [comment]
@louptheron do you have a cover slide please?

**Comment by louptheron** [comment]
Here's the slides : https://docs.google.com/presentation/d/1bLZLMVnNwhl81aEtfmPm8rMpoQ8lrsCuOoLtFilGftc/edit?usp=sharing

**Comment by moul** [comment]
Thx @louptheron
