### ISSUE TITLE
[Workshop Proposal] Brainstorm for the next chapters

### ISSUE THREAD

**Issue by lpieri** [francep2p/community#33]
#### Title

Brainstorm for the next chapters. 

#### Workshop type

- [X] Debate
- [ ] Hands-on
- [ ] [Poster creation](https://github.com/parisp2p/community/wiki/Poster-workshop)
- [ ] Course

#### Languages

- [X] 🇫🇷
- [ ] 🇬🇧

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [X] None     | [X] None     | [X] None     | [X] None     |
| [ ] Beginner | [ ] Beginner | [ ] Beginner | [ ] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Prerequisites for participants

Just you, and your smile 😊 

---

## Description of your workshop

Let's talk about the next chapters of "Paris P2P".
For example "Lyon P2P" (#10).
In October, I am going to Lyon for a long time and I would like to try to open a new chapter in Lyon.

How to do it, what are the steps.....?
Who is motivated to join me in this amazing chapter?

We can also talk about the national community, its organization, its tools...

---

## About you

* Name: **Louise or Delay** 
* Discord handle: **Delay #6452**  
* Other contact info: **@ParisP2P** 
* Other (your projects, etc...): **42 Blockchain** 

---

Related with #10 
Related with #22  
Related with #28

**Comment by moul** [comment]
<3

**Comment by moul** [comment]
Announced in #36 and here: https://p2p.paris/en/event/monthly-1/

**Comment by moul** [comment]
@lpieri is working on a report that will be pushed as a pull request or somewhere in the WIKI
