### ISSUE TITLE
Paris P2P #3 - 2019-11-06 (next)

### ISSUE THREAD

**Issue by moul** [francep2p/community#38]
## Info

* Official link: https://p2p.paris/en/event/monthly-3/
* Meetup link: https://www.meetup.com/Paris-P2P/events/263191379/

## Talks

* #32 Talk: DPOS under the hood by @louptheron 
* #47 Talk: Decentralized Reputation on the Blockchain by @PhilippeMts

**Comment by louptheron** [comment]
Ok for me to add the https://github.com/francep2p/community/issues/32 talk to this event.

**Comment by moul** [comment]
Updated! :)

**Comment by PhilippeMts** [comment]
Hello everyone,

Would we be up to add a 10-minute version of the https://github.com/francep2p/community/issues/47 talk to the schedule ?

**Comment by moul** [comment]
yep, @louptheron's talk should last ~15 minutes, so no problem

**Comment by moul** [comment]
Slides: https://docs.google.com/presentation/d/12oUY9rReLH0l9I71DL4xqoFAp8eA0bCx7qdsdENndS4/edit#slide=id.g6ad413d101_0_435
