### ISSUE TITLE
[Talk Proposal] P2P vs Lords of the Ring

### ISSUE THREAD

**Issue by zicmama** [francep2p/community#44]
#### Title

From single computers to ONE. A quest for the precious.

#### Languages

- [x] 🇫🇷
- [x] 🇬🇧

#### Estimated duration

~20 min

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [x] Beginner | [x] Beginner | [x] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory)
- [x] Yes (if possible)
- [ ] No

---

## Description of your talk

Light Client - Client / Server - P2P
- History: P2P Dark Age & Revival
- Industry 4.0: DRM, Cloud, bio-authentication, 1st & 2nd class services, money! Feodal attitude ;( 

- Precious Unique ID!
- Blockchain / Crypto = Web 3.0
- Open Source != Libre
- Politics / Media / Money

- P2P & Private copy
- Libra + Dune
- Ḡ1 = Duniter + WOT
- IPFS: Interplanetary MediaCenter + NextCloud
- Decentralized Asynchronous Mesh Internet
- REC Machine(s)
Music: https://github.com/ritiek/spotify-downloader ...
Video: https://sh.invidiou.sh/ ...

https://www.youtube.com/watch?v=H_kNnbieO7o
---

## About you

Born in 72. Pong geek. Network engineer. Linkeo.com Founder. Autonomous living tech. Volunteer for global world change.

* Name: Fred
* Matrix handle: **TODO** 
* Discord handle: **TODO**  
* Other contact info: support@qo-op.com
* Links to your previous talks: **TODO** 
* Other (your projects, etc...): MadeInZion. G1sms. Zicmama. CopyLaRadio 
* Availability (monthly number, date): 4 sept 2019 .

**Comment by pokapow** [comment]
All right dude ! =)

**Comment by aeddi** [comment]
Hey! Nice proposal :)
About the "Video recording" section, you just need to mention if you want your talk to be recorded then posted to p2p.paris website with 3 options:
- if possible (you want to be recorded if the conditions are suitable: not to noisy, light ok, etc...)
- mandatory (you want to be recorded and you prefer to postpone your talk if the conditions are not suitable)
- no (you don't want your talk to be recorded)

**Comment by moul** [comment]
I book you the last slot during the next event

**Comment by zicmama** [comment]
https://tube.p2p.legal/videos/watch/f45b8e45-df35-4189-bd71-0050ca5c375b

**Comment by moul** [comment]
@zicmama peux-tu m'envoyer un screenshot de ta presentation ou quelque chose que je peux mettre dans les slides d'intros qui presentent la soiree et les 2 talks stp ?

**Comment by moul** [comment]
No slides :)
