### ISSUE TITLE
[Talk Proposal] Decentralized Reputation on the Blockchain

### ISSUE THREAD

**Issue by PhilippeMts** [francep2p/community#47]
#### Title

Decentralized Reputation on the Blockchain

#### Languages

- [x] 🇫🇷
- [x] 🇬🇧

#### Estimated duration

\~20 min

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [x] Beginner | [x] Beginner | [ ] Beginner | [ ] Beginner |
| [ ] Advanced | [ ] Advanced | [x] Advanced | [x] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory) 
- [x] Yes (if possible) 
- [ ] No 

---

## Description of your talk

We would like to present a project aiming to build a transparent, flexible, certified and autonomous reputation system.

At the time of writing, the project is an [open-source](https://github.com/Blockchainpartner/hagentrust) proof of [concept](https://medium.com/@teamtech/blockchain-a-question-of-reputation-42626caf27fe) which could initiate broader discussions.

The solution is based on [Eigentrust](https://en.wikipedia.org/wiki/EigenTrust) reputation algorithm for P2P networks, decentralized identites and claims on blockchains, and [The Graph](https://thegraph.com/) protocol.

---

## About you

* Name: Philippe_Mts
* Matrix handle: [ioddo](@ioddo:matrix.org)
* Discord handle: phil#3651
* Other contact info: [PGP](http://metais.me/Philippe_Metais_pub.asc)
* Other (your projects, etc...): Technical blog with friends at [Blockchain Partner](https://blockchainpartner.fr/) : https://medium.com/@teamtech/
* Availability (monthly number, date): ParisP2P \#3, 2019-11-06

**Comment by zooma2k18** [comment]
Hey @PhilippeMts ! 

Great proposal, maybe you should talk with @louptheron because 2 talks (20min) on the same event is not the best line up (sound in Ground Control is more and more loud around near 8pm, and people prefer FFA, workshops & Beer2Beer time cause talk are harder to ear).  

Maybe you could be available on the #41 edition (12.04.09) @PhilippeMts for this talk ? (slot is free yet) or discuss with loup!

Just an advice, Its also ok like this, but maybe not optimum for time schedule & conditions x) 
Cheers!

**Comment by PhilippeMts** [comment]
Thanks for your review @zooma2k18,

@louptheron's talk sounds super interesting !
If that's ok with everyone, I think scaling down my proposal to a 10 minute talk could be a good challenge. I would go straight to the main points which may even make the presentation clearer.
Would that suit the schedule for [ParisP2P #3, 2019-11-06](https://github.com/francep2p/community/issues/38) ?

Otherwise, I would be happy (and available) to do it on [#41 edition on 2019-12-04](https://github.com/francep2p/community/issues/41) indeed.

Thanks for this good advice !

**Comment by Z-a-r-a-k-i** [comment]
Awesome and very interesting topic, can't wait :)

**Comment by moul** [comment]
Announce in #38

**Comment by moul** [comment]
@PhilippeMts do you have a cover slide?

**Comment by PhilippeMts** [comment]
Hello @moul , i would have the following slide :
![cover_slide](https://user-images.githubusercontent.com/1371613/68291579-72d0e100-008a-11ea-926f-5323c75c9880.jpg)

**Comment by moul** [comment]
perfect :+1:

**Comment by moul** [comment]
thank you for your presentation @PhilippeMts

can you share your slides here? :)

**Comment by PhilippeMts** [comment]
Thanks for the invite !

Sure, here they are : [Decentralized Reputation on the Blockchain.pdf](https://github.com/francep2p/community/files/3818639/Decentralized.Reputation.on.the.Blockchain.pdf)
