### ISSUE TITLE
[Talk Proposal] P2P and education (Lyon P2P)

### ISSUE THREAD

**Issue by lpieri** [francep2p/community#54]
#### Title

The P2P and the Education

#### Languages

- [x] 🇫🇷
- [ ] 🇬🇧

#### Estimated duration

~20 mins

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [x] None     | [x] None     | [x] None     | [x] None     |
| [ ] Beginner | [ ] Beginner | [ ] Beginner | [ ] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory) 
- [ ] Yes (if possible) 
- [x] No 

---

## Description of your talk

I going talk about how the P2P could be applied in education and the learning as well as the alternatives a national education.

---

## About you

* Name: **Louise P.** 
* Discord handle: **Delay #6452**  
* Other contact info: **Github: @lpieri - Mail: cpieri@student.42.fr** 
* Other (your projects, etc...): **42 Blockchain** 
* Availability (monthly number, date): **Lyon P2P #48**

**Comment by moul** [comment]
:+1: 

Talk announced here: https://github.com/francep2p/community/issues/48
