### ISSUE TITLE
Lyon P2P #1 - 2019-12-11 (next)

### ISSUE THREAD

**Issue by moul** [francep2p/community#56]
## Info

* Meetup link: https://www.meetup.com/France-P2P/events/266104402/

## Talks

* _Available slot_ 
* _Available slot_

---

Related with https://github.com/francep2p/community/issues/10

**Comment by lpieri** [comment]
🎉

**Comment by lpieri** [comment]
Crypto Lyon the community crypto at Lyon, helps me to organize the event
Their event's link: https://www.crypto-lyon.fr/event/lyon-p2p-1-%F0%9F%87%AB%F0%9F%87%B7-monthly-peer-to-beer

**Comment by lpieri** [comment]
Hello 👋 
We have 3 talks for this event:

- The P2P Learning - by @lpieri 
- Introduction to Cryptography for Developers - by @moul 
- How Bitcoin works - by Antoine Poinsot

**Comment by moul** [comment]
Closing (done)
