### ISSUE TITLE
Aeternity: scalable smart contracts + oracle machine

### ISSUE THREAD

**Issue by manelomanu** [francep2p/community#58]
Manel Ruiz, lead ambassador of Aeternity in Spain will explain how the Aeternity Blockchain works and what are its differences with the other smart contract platforms in the market. It will present the Starfleet program (next edition in 2020), the incubation program to create Dapps in Aeternity in which 8 teams have already received $ 100,000 in AE tokens and a six-month mentoring program with some of the best programmers in Europe. The attendees of the talk will be given a link so they can participate in remunerated online courses (100$) to learn how to program Smart contracts in the functional language Sophia."

Aeternity: scalable smart contracts + oracle machine

- [* ] 🇫🇷
- [* ] 🇬🇧

between 20-30 min

every crytpo enthusiast is welcome!  some part of my talk will be a bit more directed to developers and I'll invite them to do our remunerated online course(100$ in AE token) to learn the functional programming language for smart contract that we developed, Sophia.
4min- Presentation
8min - Scaling solutions
8min - Oracles
4min - mining Aeternity
6min - Starfleet program (incubation program to develop Apps in Aeternity and remunerated courses)

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [* ] Beginner | [ *] Beginner | [* ] Beginner | [* ] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [* ] Yes (mandatory) 
- [ *] Yes (if possible) 
- [ ] No 
I normally record myself with my professional camera but as you want
---

## Description of your talk

 Presentation
 Scaling solutions: Bitcoin NG and State Channels
 Oracles
 Mining Aeternity
 Starfleet program (incubation program to develop Apps in Aeternity and remunerated courses)
 Networking: Food and drinks(paid by us), airdrop of 2 Euros to each person in the audience and Aeternity t-shirts and merchandising
---

## About you

* Name: Manel Ruiz
* Matrix handle: **TODO** 
* Discord handle: Manel o Manu #5954
* Other contact info: manelomanu@protonmail.com
* Links to your previous talks: 
Aeternity Talks
Madrid
https://twitter.com/manelomanu/status/1132594994420883456?s=09
Zaragoza
https://empresason.com/not/6228/manel-ruiz-los-state-channels-permiten-transacciones-infinitas-a-cero-coste-/ EmpresasON el digital económico de Aragón https://empresason.com/not/6228/man...
Alicante
https://twitter.com/Ucoin_/status/1124750055439781893?s=19
Murcia
https://congresoblockchainmurcia.es/ 3

* Other (your projects, etc...): I represented Bitlattice in the Startup panel of the European Blockchain convention 2018 and I'm a teacher in the Blockchain Institute of Barcelona
* Availability (monthly number, date):from the 24 January to 7 February 2020 would be great

**Comment by manelomanu** [comment]
I see that you normally do meetups in the first Wednesday of the Month, what about the 5th of February?

**Comment by manelomanu** [comment]
or the 4 March, or 1rst of April 2020...up to you

**Comment by moul** [comment]
👍 thank you for this proposal :)

there are available slots for all your suggested days: #50, #51, #52 

btw, we limit the "talk time" of the whole event to 30 minutes, so ideally you should try to make a shorter version of your talk so we can have a second talk for the same evening

else, we can dedicate an evening to your talk

**Comment by manelomanu** [comment]
waw, so cool! I could do it shorter of course, the 5th february its great then!
if you want we can do the drinks and snacks and airdrop at the end of the afternoon

**Comment by manelomanu** [comment]
"else, we can dedicate an evening to your talk" but when?I guess the days I suggested have other talks booked, isn't it?

**Comment by manelomanu** [comment]
well, I think 30 minutes will be enough in the 5th of February, if you want we can do the networking at the end.

**Comment by moul** [comment]
Hi @manelomanu, now that the festival is over, I try to check if the different open topics are still active

Do you still want to make this talk? Still on 5th of February?

🙏

**Comment by manelomanu** [comment]
Yes men, 100%!
I loved the festival!

Enviado desde ProtonMail móvil

-------- Mensaje original --------
