### ISSUE TITLE
[Talk Proposal] Cjdns and PKT : Decentralizing Internet Infrastucture

### ISSUE THREAD

**Issue by cjdelisle** [francep2p/community#60]
#### Title

Cjdns and PKT : Decentralizing Internet Infrastucture

#### Languages

- [ ] 🇫🇷
- [x] 🇬🇧

#### Estimated duration

45min + 15min questions, flexible.

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [x] None     | [ ] None     | [ ] None     |
| [x] Beginner | [ ] Beginner | [x] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory) 
- [x] Yes (if possible) 
- [ ] No 

---

## Description of your talk

8 years ago cjdns was started to make the internet encrypted and decentralized, unlike TOR and I2P, it was not intended as an overlay but rather to a complete revisit of the way the internet should work, peer-to-peer and always encrypted. Since then it has had moderate community interest but has not lead to any actual infrastructure buildout.

My current project is a sort of phase-two of cjdns, building a blockchain called [PKT](https://pkt.cash/) in order to create a *bandwidth market* so that anyone capable of running fiber and pointing antennas can participate in building the infrastructure of the new internet. All of these fibers and wireless links will become a "pool of bandwidth" which a professional network operator can reach into and pull out the bandwidth necessary to build their own network.

This talk aims to limit technical details to the minimum that is necessary so please do not feel intimidated to attend. There will be time reserved for questions so that in case there is not enough technical detail, topics can be addressed more fully.

---

## About you

* Name: Caleb James DeLisle
* Matrix handle: @cjdelisle:m.trnsz.com
* Links to your previous talks:
  * https://www.youtube.com/watch?v=3cLwh7YR6Sc
  * https://media.ccc.de/v/34c3-9072-bgp_and_the_rule_of_custom
* Other (your projects, etc...):
  * https://github.com/cjdelisle/cjdns
  * https://pkt.cash/
* Availability (monthly number, date):
  * flexible

**Comment by moul** [comment]
thank you @cjdelisle for you talks during the festival :+1:

**Comment by 3nprob** [comment]
@cjdelisle @moul Any chance that recording is available somewhere? :)

EDIT: Think I found it: https://piped.kavin.rocks/watch?v=-xgRUAA_p5E

**Comment by cjdelisle** [comment]
Here it is: https://www.youtube.com/watch?v=-xgRUAA_p5E
Sound is not excellent because it was not recorded off the PA but it exists.
